name: moirai2
channels:
  - defaults
dependencies:
  # minimal conda base for a clean Python 3.11 env
  - python=3.11.13
  - pip=25.1
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - readline
  - sqlite
  - tk
  - xz
  - zlib
  - git  # needed to pip-install uni2ts from GitHub
  - pip:
      # Core runtime
      - torch==2.4.1           # macOS arm64 wheel w/ MPS support
      - numpy==1.26.4
      - pandas==2.1.4
      - matplotlib==3.9.2
      - tqdm==4.66.3

      # Moirai2 + friends
      - gluonts==0.14.4        # GluonTS helpers used by uni2ts examples
      - huggingface_hub==0.33.1
      - datasets==2.17.1

      # Pull latest uni2ts (includes Moirai-2.0 classes)
      - "git+https://github.com/SalesforceAIResearch/uni2ts.git#egg=uni2ts"
