name: try_tsfm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - pytorch
  - pip
  - pip:
      - git+https://github.com/amazon-science/chronos-forecasting.git@mlx
      - gluonts
      - uni2ts
      - git+https://github.com/NX-AI/TiRex.git
      - rotary-embedding-torch
